<a href="https://colab.research.google.com/github/yui-miffy/Python/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#配列
import numpy as np
data=np.array([9,2,3,4,10,6,7,8,1,5])
data


array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [8]:
#乱数の発生
import numpy.random as random
random.seed(0)
rnd_data=random.randn(10)
print("乱数10個の配列:",rnd_data)

乱数10個の配列: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]


In [9]:
#抽出対象データ
data=np.array([9,2,3,4,10,6,7,8,2,5])
#ランダム抽出
#10個を抽出(重複あり、復元抽出)
print(random.choice(data,10))
#10個を抽出(重複なし、非復元抽出)
print(random.choice(data,10,replace=False))

[ 7  8  8  2  2  6  5  2  5 10]
[10  2  7  8  3  2  6  5  9  4]


In [11]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
array1=np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
array2=np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [16]:
#行列の積
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])